DWAPlannerROS:
  max_vel_x: 0.15
  min_vel_x: -0.02
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.3
  min_vel_trans: -0.3

#trans_stopped_vel:0.01
  max_vel_theta: 0.5
  min_vel_theta: 0.1

  #rot_stopped_vel:0.01
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.0

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.05

  sim_time: 3.5  #3.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 50

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.04
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.1

  publish_traj_pc: true
  publish_cost_grid_pc: true
  global_frame_id: base_footprint_link

