DWAPlannerROS:
  max_vel_x: 0.18
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.18
  min_vel_trans: -0.18
#trans_stopped_vel:0.01
  max_vel_theta: 1.8
  min_vel_theta: 0.7

  #rot_stopped_vel:0.01
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 2.0

  yaw_goal_tolerance: 0.30
  xy_goal_tolerance: 0.3

  sim_time: 3.5  #3.5
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.04
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.1

  publish_traj_pc: true
  publish_cost_grid_pc: true
  global_frame_id: odom

